name: Run unit tests for Scalr

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: conanio/${{matrix.tag}}:latest
    strategy:
      matrix:
        tag: [gcc5, gcc6, gcc7, gcc8, gcc9, gcc10, gcc11]
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: make test
