name: Test scalr

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: gcc:${{matrix.tag}}
    strategy:      
      matrix: 
        tag: [5, 6, 7, 8, 9, 10]
    steps:
    - uses: actions/checkout@v2
    - name: make test
      run: CC=gcc CXX=g++ make test

