name: Test scalr

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: conanio/${{matrix.conan_image}}
    strategy:      
      matrix: 
        conan_image: [gcc5, gcc6, gcc7, gcc8, gcc9, gcc10]
    steps:
    - uses: actions/checkout@v2
    - name: make test
      run: make CC=gcc-${{matrix.gccVersion}} CXX=g++ test

